### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by valbuz** [baerengraben/ioBroker.swiss-weather-api#1]
Hi

Dies zur Deine rInfo.
Gruss
Pat

swiss-weather-api.0 | 2020-01-29 08:27:02.157 | info | (31386) Icon could not be found. Please create an issue on github. Icon number was: -29
-- | -- | -- | --
swiss-weather-api.0 | 2020-01-29 08:27:02.153 | info | (31386) Icon could not be found. Please create an issue on github. Icon number was: -20

**Comment by baerengraben** [comment]
Hi Pat
Vielen Dank für das Issue. :)
Ich bin bereits diesbezüglich mit SRG-SSR in Kontakt. Das API liefert hier undokumentierte Icon-Codes an. Ich veröffentliche eine neue Version sobald ich die notwendigen Infos erhalten habe.
Gruss
Ralph

**Comment by valbuz** [comment]
Hallo Ralph

Danke für Deine Rückmeldung.

Patrick

Am Mi., 29. Jan. 2020 um 12:59 Uhr schrieb baerengraben <
notifications@github.com>:

**Comment by baerengraben** [comment]
Habe eine neue Version "0.1.7" erstellt. Diese berücksichtigt nun Codes bis -30. Die Codes wurden aber noch nicht offiziell von SRG bestätigt. Deswegen ist diese Version nicht in "stable" sondern kann nur über den "latest" branch abgerufen werden. Sobald die SRG die Codes bestätigt hat, wird eine neue Version erstellt und in den stable branch gemerged.

**Comment by baerengraben** [comment]
Die Icons wurden von SRG geliefert und in Version 0.1.8 integriert, inkl. den neuen Codes.
