### ISSUE TITLE
data type number statt string

### ISSUE THREAD

**Issue by thGirard** [baerengraben/iobroker.swiss-weather-api#10]
Darf ich nochmals einen Kommentar machen?
Es wäre super, wenn die numerischen Datenpunkte (ddd, fff, ffx3, pr3, rr3, ttt als Datentyp 'numeric' an Stelle von 'string' hätten.
Der Grund ist, dass ich in VIS gerne einen cutoff in visibility setze (also zB icon für Regen nur wenn pr3 < 40%)
Danke 
Thierry

**Comment by baerengraben** [comment]
Implementiert mit 0.2.2
