### ISSUE TITLE
V2.0.4-alpha: Objekte erst dann löschen, wenn ein SRF Response erfolgreich

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#103]
Neu lösche ich bei jedem erstellen der Objekte vorgängig alle Objekte. Hintergrund ist, dass SRF teilweise nicht einen kompletten Objekt-Satz zustellt. Teilweise werden nur partielle Daten geliefert (wieso auch immer). Nachteil ist, dass bei einem Run mit unvollständigen Daten, Objekte mit einem veralteten Zustand zurückbleiben (jene Objekte für die es kein Update gab, aber eines gebe müsste). Mit dem Löschen aller Objekte stelle ich sicher, dass immer nur die aktuellsten Daten vorhanden sind. Im schlimmsten Falle fehlen halt Daten, welche dann mit einem späteren Run (mit komplettem Datensatz) wieder befüllt werden.

Nun kann es aber sein, dass beim SRF-Fehler "too many requests" gar keine Daten geliefert werden. In diesem Falle bleibt der Adapter ohne Daten, weil vor dem Request bereits alle Objekte gelöscht wurden 
Hier muss die Reihenfolge verbessert werden. Erst sollen erst die Daten gelesen werden und dann, wenn Daten geliefert wruden, vorgängig die alten Objekte löschen und wieder neu erstellen.

**Comment by tops4u** [comment]
@baerengraben ja das ist Super unpraktisch. Ich verwende teils Datenpunkte in Scripts und Anzeigen. Diese werden dann Null, GitHUB Wetter Icons sind dann tote Bild-Links und Scripts failen dann teilweise. 
Zum Beispiel verwende ich Daten zum Steuern von Sonnenstoren etc. Sind die Daten nicht vorhanden, dann zieht das nicht und die Store bleibt drin. Gerade in den kommenden Tagen ist da eine funktionierende Steuerung schon wünschenswert - insb wenn man selbst eben nicht zuhause ist.

**Comment by baerengraben** [comment]
Es gab mittlerweile diverse Feedbacks zu diesen Thema. Ich nehm das in der nächsten Version so wieder raus. - War nicht die beste Idee.

**Comment by tops4u** [comment]
Ja bitte wieder rausnehmen :-)

Besten Dank für den Adapter welcher für die CH IoBroker Nutzer sehr nützlich ist. Merci.
