### ISSUE TITLE
Influxdb recording deletet after 30min

### ISSUE THREAD

**Issue by photonicsGPC** [baerengraben/ioBroker.swiss-weather-api#105]
The recording to the influxdb database is resetted every 30min. Is this due to the fact that the whole tree of the objects is deleted?

**Comment by baerengraben** [comment]
Are you using Version 2.0.4-alpha.0 (2023-08-03) ?

**Comment by photonicsGPC** [comment]
Yes i use the version 2.0.4-alpha. I'm totally aware off that this releasevcan have somevissues. So farm i made a workaround by storing the values in datapoints. I look forward to the next release. Thanks for your great work on this adapter. Greez
