### ISSUE TITLE
Please consider creating a "normal" release 2.0.4

### ISSUE THREAD

**Issue by mcm1957** [baerengraben/ioBroker.swiss-weather-api#107]
As 2.0.4-alpha.x is available since some time, please consider creating a normal release so that the new release will can get available at (stable) repositories.

Thanks

**Comment by mcm1957** [comment]
Just a kind reminder...
Do you need any help?

**Comment by baerengraben** [comment]
I'm aware of this. But no help needed. Thanks for asking!

**Comment by baerengraben** [comment]
New Release 2.1.0
