### ISSUE TITLE
Fehlende Icon

### ISSUE THREAD

**Issue by Zerpac54** [baerengraben/ioBroker.swiss-weather-api#108]
Wie ich heute gesehen habe fehlen die ersten zwei Logos im Detailview_0
swiss-weather-api.0.forecast.hours.day0.0400.ICON_URL_COLOR
Kann ich die irgendwo sehen?

**Comment by baerengraben** [comment]
Mir ist das die letzten Tage auch aufgefallen. Eigentlich verwende ich nur dokumentierte Icons von SRF. Ich werde bei Gelegenheit (sobald ich wieder einen Fall beobachte) mal  herausfinden, welches Icon konkret fehlt. Dann kann ich es ergänzen.

**Comment by baerengraben** [comment]
Ich habe den Fall gerade wieder. Es wird nach dem Icon ioBroker.swiss-weather-api/master/img/Meteo_API_Icons/Color/0.png gesucht. Für "0.png" existiert aber gar kein Icon (gem. SRF Meteo API). Die Frage stellt sich also, wieso hier das SRF-API ein 0.png meldet, aber gar kein Icon spezifiziert. => Werde als nächstes mal die Response-Daten debuggen.

**Comment by baerengraben** [comment]
Antwort von SRF ist eingetroffen:

_symbol_code "0" ist vor kurzem aufgetreten wegen einem Fehler bei der Datengenerierung. Der Code wurde nun angepasst und das sollte so nicht mehr auftreten._

**Comment by Zerpac54** [comment]
Super, danke für die schnelle Erledigung.
