### ISSUE TITLE
Forecast - An error has occured. {"code":"500.02.001","message":"Internal server error","info":"https://developer.srgssr.ch"}

### ISSUE THREAD

**Issue by EschLuAB** [baerengraben/ioBroker.swiss-weather-api#110]
Seit heute heute 1 Uhr bekomme ich diesen Fehler.
Habe mal die Forecast  Objekte gelöscht und dann kommen nur noch folgende Objekte (siehe Forecast.jpg)
![Forecast](https://github.com/baerengraben/ioBroker.swiss-weather-api/assets/117769973/d1888864-f682-447a-bb82-bd7223e71c41)

Hat sonst jemand das selber Problem?
Fehlerquelle auf Seite SRG-Server?

HG Armin

**Comment by baerengraben** [comment]
Ein 500er Fehler deutet auf ein Problem beim SRF-API hin. Welche Longitude&Latitude frägst du ab? Dann teste ich das mal bei mir.

**Comment by EschLuAB** [comment]
Danke für Dein Feedback und Dein Hilfsangebot.
Habe die Instanz vor etwas mehr als einer Stunde wieder gestartet und nun geht es.
Zumindest waren die letzten zwei Abfragen erfolgreich.

Was ich eher speziell fände, wenn genau nur meine Longitude&Latitude davon betroffen gewesen sind. :-)
Wenn dem so ist, dann ist es Zeit, einen Lottozettel auszufüllen ;-)
Erachte es als ein gutes Omen!
