### ISSUE TITLE
Forecast - An error has occured: location mismatch for developer app

### ISSUE THREAD

**Issue by abeggled** [baerengraben/ioBroker.swiss-weather-api#114]
Seit ein paar Tegen kriege ich diese Fehlermeldung mit der Version 2.1.0:
`Forecast - An error has occured. {"code":"400.01.007","message":"location mismatch for developer app","info":"You have exceeded your location limit"}`
Grundsätzlich scheint der Adapter aber zu funktionieren.

**Comment by SwissSteini** [comment]
Habe das gleiche Problem seit letzten Mittwoch 14.2. mit Version 2.0.3 und 2.1.0
Der Adapter steht auf Orange

**Comment by cyrillbaumgartner** [comment]
Hallo Zusammen, gleiches Problem....

**Comment by robertfraefel** [comment]
Habe das selbe Problem!

**Comment by knowhowseeker** [comment]
Gleiches Problem!

**Comment by tops4u** [comment]
Ja gleiches Problem hier. Habe auch schon versucht die API bei der SRG neu anzulegen, leider ohne Erfolg.

**Comment by dthurnheer** [comment]
Ich habe leider auch das gleiche problem seit ein paar Tage.

**Comment by Zerpac54** [comment]
habe leider das gleiche Problem. Adapter 2.1.0 bleibt orange. Habe andere Keys generiert ohne Erfolg.

**Comment by baerengraben** [comment]
Kann das Problem bestätigen - ich schaue es mir an

**Comment by baerengraben** [comment]
Ich denke ich habe das Problem erkannt:

- Das SRF-API erlaubt bekannterweise die Abfrage für Wetterprognosen für alle Längen-/Breitengrade in der Schweiz
- Aber 100%ig stimmt das nicht. Genaugenommen liefern wir unsere Längen-/Breitengrade und das SRF-API liefert uns dann eine korrespondierende Geo-Location über welche dann wiederum effektiv die Prognose abgerufen wird.
- Grundsätzlich liefert das API logischweise für die Längen-/Breitengrade immer die gleiche Geo-Location
- Irgendwie haben sie aber wohl etwas geändert. Ich erhalte heute nicht mehr die gleiche Geo-Location, wie ich noch vor 3 Wochen erhalten habe.
- Nun, das jetzt eine etwas andere (aber für Wetterinfos immer noch gute) Geo-Location daherkommt ist nicht weiter schlimm. Dann liefert halt das API die Prognosen dieser etwas veränderten Geo-Location => Das Könnte man meinen.

Aber leider erlaubt ein Freemium-Abo eben immer nur die Abfrage einer einzigen Geo-Location. Wenn man also Abfragen mit dem Adapter gemacht hat, verknüpft die SRG diese eine Geo-Location mit dem SRG-Account. Wenn nun aber das API plötzlich eine andere Geo-Location für die Längen-/Breitengrade liefert, schlägt diese Limite zu und verweigert die Auslieferung von Wetterdaten für den bisherigen SRG-Account.

Bereits geprüfter Work-Around (leider): 
- Komplett neuen Account anlegen und Freemium-App hinzufügen
- Dann die neuen ConsumerKey und ConsumerSecrets in dem Adapter hinterlegen

Damit wird dem neuen Account die neue Geo-Location verknüpft und der Adapter geht wieder.

Das ist aber wirklich nur ein Work-Around. Eigentlich müsste das API immer für die Längen-/Breitengrade die korrespondierende gleiche Geo-Location anbieten. Wieso dies geändert hat, muss ich jetzt noch bei SRG nachfragen.

**Comment by SwissSteini** [comment]
Der Workaround funktioniert bei mir. Vielen Dank

**Comment by robertfraefel** [comment]
Hat bei mir nicht funktioniert. Habe es 2 Mal versucht. Muss ich beim Adapter die Geo-Location angeben? Hatte dort immer leer damit er die vom iobroker system nimmt.

**Comment by baerengraben** [comment]
Hast du bei SRG einen komplett neuen Account erstellt (https://developer.srgssr.ch/user/register)?

**Comment by robertfraefel** [comment]
nein, nur eine neue "App"! Habe das zu wenig genau gelesen....

**Comment by tops4u** [comment]
Hat bei mir geklappt, besten Dank @baerengraben !

Schade ist das so gelöst und noch weniger begeistert mich die SRG - auf meine Anfrage zu dem Problem vor 2 Wochen kam 0 Antwort. Schade!

**Comment by dthurnheer** [comment]
Bei mir hat es auch geklappt. Vielen Dank für den Workaround.

**Comment by Zerpac54** [comment]
Danke, diese Info hat bei mir auch funktioniert. Ich denke aber, wenn man das System runter fährt passiert das wieder

**Comment by baerengraben** [comment]
Ich habe inzwischen bereits Feedback von SRG bekommen. Sie analysieren aktuell meine Anfrage.

**Comment by baerengraben** [comment]
Ich habe inzwischen bereits Feedback von SRG bekommen. Demnach haben sie das Problem behoben. Kann jemand mal bitte testen, ob es jetzt mit den "alten" ConsumerKey und ConsumerSecret wieder funktioniert? Ich bin gerade unterwegs und kann nicht testen.

**Comment by SwissSteini** [comment]
Bei mir funktioniert es auch mit den alten Key wieder.
Danke fürs abklären!

**Comment by cyrillbaumgartner** [comment]
Hallo Zusammen,
Vielen Dank, Neustart Adapter und funktioniert bei mir auch!
