### ISSUE TITLE
Install Issue Node-V72

### ISSUE THREAD

**Issue by CyberSponk** [baerengraben/iobroker.swiss-weather-api#12]
Grüezi,

beim Versuch den Adapter zu installieren bekomme ich die Fehlermeldung:

_https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v72-linux-arm-glibc.tar.gz not found._

Der Adapter funktioniert dann nicht.

Grüsse
Nick

**Comment by baerengraben** [comment]
Hi @CyberSponk 
Kannst du mir bitte noch mehr Informationen zu deiner Umgebung mitteilen? Wo/Wie läuft bei dir ioBroker (System und Version)?
Vielen Dank und Grüsse

**Comment by CyberSponk** [comment]
Hi,

das ging irgendwie unter. Ich habe einen _Pi 3 B Rev. 1.2_ mit _Raspbian Buster_. Darauf den _ioBroker 4.0.10_ und hier wieder _js-controller 3.1.6_. Benötigst Du noch weitere Infos?

Grüsse
Nick

**Comment by baerengraben** [comment]
Hi Nick
Ich kann mir den Fehler aktuell noch nicht erklären. Kannst du bitte mal versuchen die neueste Version 0.2.3 zu installieren?
Grüsse
Ralph

**Comment by baerengraben** [comment]
Aufgrund von Inaktivität geschlossen.
