### ISSUE TITLE
instance system.adapter.swiss-weather-api.0 already running with pid XXXXX

### ISSUE THREAD

**Issue by zImage-de** [baerengraben/iobroker.swiss-weather-api#16]
I got the WARN messages in Log: 
instance system.adapter.swiss-weather-api.0 already running with pid XXXX

swiss-Weather-api Version 0.3.0

**Comment by baerengraben** [comment]
Hi
This log entry is not necessarily a problem. It just says that iobroker wanted to start the adapter, but the adapter was already running. Does the adapter work?
