### ISSUE TITLE
Write Sunshine duration and precipitation in datapoint

### ISSUE THREAD

**Issue by Aare07** [baerengraben/iobroker.swiss-weather-api#18]
Is there a posibility to get the  the sun hours in h, the probrain in % and the precipitation in the six days forecast?
These are on the srf meteo website visible and as datapoints in the 24 hours forecast.
but i did not find them in the six days forecast, only the icontype.

Ist this a limitation of the free API, the adapter or did i miss some settings?

My goal is tho forecast the photovoltaic power of the next day to make an decision to switch on the heater during the cheap night perjod or wait and run it on the next day with my own pv power.
Thanks and greetings from a neighbour
Aare

**Comment by baerengraben** [comment]
Hi

Unfortunately, detailed weekly forecasts are not delivered via the "non-commercial" API. The non-commercial API only provides detailed information about the current day (24h forecast). 

But you can still implement your logic. The non-commercial API delivers the current day values already from 1:00 in the night. If you execute your logic (loading at night or during the day) after 1:00 am at night, this should also work with the non-commercial API.

Greetings
Ralph

**Comment by Aare07** [comment]
Hi Ralph
I will go with the 24 h dataset.  
I was wrong with my 24 / 7 hour tought that it is only an 7 hour forecast. Now i see this dataset ist true 24h in 3 h steps... 
Ok. The expected sun hours are also not in the data but i take the icon to guess PV power estimation. Will work. 
Issue solved.
Thank you
Greetings Aare
