### ISSUE TITLE
Kein Fehler, aber frage zum Einbinden eines Wertes

### ISSUE THREAD

**Issue by trevon88** [baerengraben/ioBroker.swiss-weather-api#21]
Wäre es möglich das du ein Beispiel in der Anleitung zeigst, wie man einen Wert bekommen kann?
Ich hab nun mehrere Sachen Versucht, bekomme aber keine Werte in VIS angezeigt.

Manchmal erhalte ich im LOG:

swiss-weather-api.0 | 2020-12-12 15:02:35.914 | error | (19814) Week Forecast - Requested Location is not supported. Please be aware, that this adapter only supports locations within Switzerland.
-- | -- | -- | --
swiss-weather-api.0 | 2020-12-12 15:02:35.910 | error | (19814) Hour Forecast - Requested Location is not supported. Please be aware, that this adapter only supports locations within Switzerland.
swiss-weather-api.0 | 2020-12-12 15:02:35.907 | error | (19814) 24h Forecast - Requested Location is not supported. Please be aware, that this adapter only supports locations within Switzerland.
swiss-weather-api.0 | 2020-12-12 15:02:35.902 | error | (19814) Current Forecast - Requested Location is not supported. Please be aware, that this adapter only supports locations within Switzerland.

Mit dem Zürich Beispiel, naja, vielleicht ist eine "API" einfach nichts für Anfänger :P

Danke

**Comment by baerengraben** [comment]
Hi @trevon88 

Du kannst das einfach einstellen, indem du in den ioBroker-Einstellungen (Haupteinstellungen) deinen Standord einstellst (über die Map). Dabei wird Längen- und Breitengrad gesetzt. Im swiss-weather-api kannst du dann die Felder Längen- und Breitengrade leer lassen. Der Adapter übernimmt dann die Einstellungen des ioBrokers.

=> Ich werde das im nächsten Release noch besser dokumentieren :)

**Comment by baerengraben** [comment]
ist nun ab version 0.9.0 besser dokumentiert.
