### ISSUE TITLE
Anfrage für neuen Wert

### ISSUE THREAD

**Issue by danimeierch** [baerengraben/iobroker.swiss-weather-api#25]
Guten Tag! Der Adapter ist sehr gelungen und funktioniert bestens. Herzlichen Dank dafür! Wäre es möglich, noch einen weiteren Wert einzufügen? Nämlich, ob es während der selektionierten Forceast-Zeit regnet? Zum Beispiel bei "current_day". Das man weiss, ob es irgendwann im Laufe des Tages regnen wird. Danke für's Prüfen!

**Comment by baerengraben** [comment]
hallo @danimeierch 

Diese Info wird vom Adapter (bzw. von SRG) über die Regenwahrscheinlichkeit bereits geliefert:

- current_hour_pr3_probrain_3h
- next_hour_forecast_pr3_probrain_3h
- twentyfour_forecast_hour1-7_pr3_probrain_3h

Diese Werte beinhalten jeweils die Regenwahrscheinlichkeit in %. Reicht das so?

**Comment by danimeierch** [comment]
Hallo @baerengraben !

Danke für die Antwort! Diese Werte habe ich bisher nicht der Regenwahrscheinlichkeit zugeordnet, danke für den Hinweis. Ich habe komischerweise jedoch nicht alle von dir genannten Werte auf meiner Liste. Vorallem der twentyfour_forecast_hour1-7_pr3_probrain_3h fehlt mir. Oder wird der nur geliefert, wenn der Wert über 0 ist?

<img width="1154" alt="objects_-_ioBroker" src="https://user-images.githubusercontent.com/17731349/108832890-6698cc00-75cc-11eb-99a5-2bf783903763.png">

<img width="1162" alt="Cursor_und_objects_-_ioBroker" src="https://user-images.githubusercontent.com/17731349/108832883-64cf0880-75cc-11eb-8683-5324a71bb982.png">

**Comment by baerengraben** [comment]
Hallo @danimeierch 
Oh, sorry. Da war ich zu ungenau. Mit "twentyfour_forecast_hour1-7_pr3_probrain_3h" verstehe ich genau die "pr3"-Werte, welche du gepostet hast. Im 24hForecast gibt es hour0 - hour7. Und darin jeweils die Regenwahrscheinlichkeit "pr3".

**Comment by danimeierch** [comment]
Hallo @baerengraben 

Danke dir vielmals. Aber das würde bedeuten, ich kann lediglich die nächsten 7 Stunden abfragen und somit keine Aussage mache, ob es im Laufe des Tages gemäss Prognose regnen wird, sondern nur, ob es in den nächsten 7 Stunden. Da ich gerne am Morgen eine Info haben möchte, ob es bis am Abend regnet ist das natürlich etwas wenig. Oder interpretiere ich dies falsch? Danke dir!

**Comment by baerengraben** [comment]
Hallo @danimeierch

Doch, das geht. Der 24hForecast liefert zwar nur 8 Objekte (hour0 - hour7), aber diese sind nicht pro Stunde sondern pro 3 Stunden zu verstehen:

- hour0: liefert Vorhersage für 1:00 
- hour1: liefert Vorhersage für 4:00 
- hour2: liefert Vorhersage für 7:00 
- hour3: liefert Vorhersage für 10:00 
- hour4: liefert Vorhersage für 13:00 
- hour5: liefert Vorhersage für 16:00 
- hour6: liefert Vorhersage für 19:00 
- hour7: liefert Vorhersage für 22:00

Was beim 24hForecast vielleicht etwas verwirrlich ist:
Die Daten für den 24hForecast werden jeweils über den Tageswechsel aktualisiert. Du erhältst also die Detail-Werte für die 24hVorhersage für den Tag erst ab 00:00 Uhr. Allfällige Steuerungs-Logik (wie z.B. das Laden des Speichers über PV vs. Stromversorger kannst du also erst ab 00:00 Uhr lostreten. Ich mache das so, funktioniert tadellos :)

**Comment by danimeierch** [comment]
Danke vielmals für die klärenden Worte...jetzt hab ich's wirklich verstanden und es klappt einwandfrei. Cool, danke!!
