### ISSUE TITLE
Kein Fehler, nur Anfrage bezüglich Datenpunkten in ioBroker

### ISSUE THREAD

**Issue by daes10** [baerengraben/iobroker.swiss-weather-api#26]
Finde in den Docs der Api irgendwie nicht zur näheren Beschreibung der einzelnen Datenpunkte.

1. Frage: Mich nimmt es Wunder wieso in 24h_forecast => hour_0 => values, nicht die gleichen Werte drin stehen wie in Current_Forecast => current_hour => values. Verstehe ich das richtige das beide die aktuelle Stunde anzeigen? Wieso sind dann zBsp. die Windgeschwindigkeiten anders?

2. Frage: <temperature_2m_act in °C> steht für "Temperatur die für 2 min gilt in Grad Celsius? oder was versteht der Wert unter "2m"?
Genau das Gleiche für: "precipitation_1.5m_sum_3h in mm" komme hier mit der Bezeichnung irgendwie nicht klar, was diese Bedeuten soll?

3. Frage: Gibt es einen Datenpunkt mit der Luftfeuchtigkeit in Prozent? Ist dies der Datenpunkt: "probrain_3h in %"?

4. Frage: Und welches Widget in VIS benutzt ihr um die Icons per url (also https) abzurufen? Kriege nicht hin dass die Icons angezeigt werden.

Ich hoffe es kann mich jemand aufklären. Bastle mir nämlich gerade eine VIS zusammen.

lg Dave

**Comment by baerengraben** [comment]
Hi Dave

Grundsätzlich liefert der Adapter einfach 1:1 die Datenpunkt-Bezeichnungen und -Werte, welche vom SRG offen zur Verfügung gestellt werden. Ich habe den Adapter so implementiert, verwende aber selber längst nicht alle Datenpunkte. 
Tatsächlich müsste ich mich aber mal um die Dokumentation aller Datenpunkte kümmern. Auch vom SRG gibt es dazu keine ausführliche Doku (zumindest habe ich bisher keine gefunden). Sie würden aber sicherlich auch Hilfestellung bieten. => Ich nehme das auf die Todo-Liste.

Zu deinen Fragen

> Frage: Mich nimmt es Wunder wieso in 24h_forecast => hour_0 => values, nicht die gleichen Werte drin stehen wie in Current_Forecast => current_hour => values. Verstehe ich das richtige das beide die aktuelle Stunde anzeigen? Wieso sind dann zBsp. die Windgeschwindigkeiten anders?

Der Datenpunkt  24h_forecast => hour_0 => date liefert hier Klarheit. In 24h_forecast => hour_0 befinden sich die Werte für 01:00 des entsprechenden Tages. Wenn du Current_Forecast => current_hour => date anschaust, siehst du für welche Stunde die Werte gelten (aktuell steht da bei mir 22:00).
Wenn ich nun die Werte 24h_forecast => hour_7 mit Current_Forecast => current_hour vergleiche, also beides Datenpunkte für 22:00 Uhr, dann sind die Werte gleich.
 
> Frage: <temperature_2m_act in °C> steht für "Temperatur die für 2 min gilt in Grad Celsius? oder was versteht der Wert unter "2m"?
Genau das Gleiche für: "precipitation_1.5m_sum_3h in mm" komme hier mit der Bezeichnung irgendwie nicht klar, was diese Bedeuten soll?

Den Datenpunkt "temperature_2m_act in °C" ist wohl die vorhergesagte Temperatur gem. date-Datenpunkt. Meine Erfahrung hat gezeigt, dass das so stimmig ist. Für was "2m" da genau steht, müsste ich bei SRG nachfragen. Den Datenpunkt  "precipitation_1.5m_sum_3h in mm" ist nach meiner Erfahrung  die  "Regenmenge in mm  in den nächsten 3h" (die 24h Vorhersage wird ja nicht stundenweise, sondern alle 3h geliefert).

> Frage: Gibt es einen Datenpunkt mit der Luftfeuchtigkeit in Prozent? Ist dies der Datenpunkt: "probrain_3h in %"?

Der Datenpunkt "probrain_3h in %" ist die Regenwarhscheinlichkeit in den nächsten 3h in %. Die Luftfeuchtigkeit wird leider in der "Free Edition" des SRG-APIs nicht mit geliefert. 

> Frage: Und welches Widget in VIS benutzt ihr um die Icons per url (also https) abzurufen? Kriege nicht hin dass die Icons angezeigt werden.

Ich selber benutze den ioBroker  lediglich zum Abfragen der Werte. Meine Visualisierung läuft nicht auf dem ioBroker. Deswegen gibt es auch keine spezielle Visu für den Adapter. => Aber wenn jemand eine schöne Visu für den Adapter liefern möchte - you can always contribute :)
Für Unterstützung bei der Implementierung einer ioBroker Visu kann ich das Forum empfehlen: https://forum.iobroker.net/category/7/visualisierung

LG Ralph

**Comment by daes10** [comment]
Hallo Ralph

Vielen Dank für deine ausführliche Hilfe.
Werde mich wahrscheinlich demnach einmal mit SRF in Verbindung setzen, um eine genauere Beschreibung der Datenpunkte anzufragen.
Falls ich mehr weiss werde ich es dir melden.

Zur VIS:
Hast du mich vermutlich falsch verstanden. Ich wollte kein fertiges Widget, sondern wollte wissen ob jemand weiss, wie ich von der icon url die ich im icon datenpunkt erhalte, das icon korrekt in VIS angezeigt bekomme. Bei mir erscheint irgendwie nichts.

Falls es Leute gibt die es interessiert:
Habe es nun anderst gelöst:

Es gibt einen Datenpunkt an dem die Symbol ID angegeben wird. (-30 bis +30).
Mit einem Blockly Skript schreibe ich alle Parameter in positive Zahlen um, da es zu jedem code 1-30 ein Bild dazu gibt (Download der Icons auf der SRF API Meteo Seite). Diese habe ich heruntergeladen und in VIS eingefügt und werden jetzt je nach Wettercode angezeigt.

Bin nun happy... ;)
