### ISSUE TITLE
Nighttime icons from SRG

### ISSUE THREAD

**Issue by UncleSamSwiss** [baerengraben/ioBroker.swiss-weather-api#28]
I know you are not the creator of the original SRG images, but it would be great to have the nighttime icons (negative value) with the moon instead of the sun, it looks a bit weird in my 24-hour display:
![image](https://user-images.githubusercontent.com/7595126/109924001-e9eaa980-7cbf-11eb-8f24-0cb3480c9c55.png)

Funny enough, in the [code table](https://developer.srgssr.ch/sites/default/files/SRG-SSR%20-%20Weather%20API%20Translations.pdf) SRG actually mentions "moon" for negative values. And also on their website the icons are correct:
![image](https://user-images.githubusercontent.com/7595126/109924235-42ba4200-7cc0-11eb-838e-380600537b4c.png)

**Comment by baerengraben** [comment]
Hi @UncleSamSwiss 
when i wrote the adapter, i asked SRG for the moon icons. Unfortunately, they never answered that request. Only the day icons they have published at that time on my request. I will ask again. Maybe i will have more luck this time.

**Comment by baerengraben** [comment]
today i asked srg again. let's wait for their answer.

**Comment by baerengraben** [comment]
with Version 0.9.0 also night icons are provided.
