### ISSUE TITLE
Date/time values are wrong by the GMT offset

### ISSUE THREAD

**Issue by UncleSamSwiss** [baerengraben/ioBroker.swiss-weather-api#29]
All reported date/time values are actually off by the GMT offset:

At 08:41 the value of `swiss-weather-api.0.CurrentForecast.current_hour.date` is `Thu Mar 04 2021 10:00:00 GMT+0100 (Central European Standard Time)` (copied from ioBroker Admin), but in my opinion it should be `Thu Mar 04 2021 09:00:00 GMT+0100 (Central European Standard Time)`.

The offset is even more obvious for the 24 hour forecast: it starts at 01:00 and increments by 3 hour steps to 22:00, but it should start at 00:00 and go through 21:00.

**Comment by baerengraben** [comment]
Should now be ok with version 0.9.0.
