### ISSUE TITLE
Der Dienst liefert keine Daten mehr

### ISSUE THREAD

**Issue by Luedem25** [baerengraben/iobroker.swiss-weather-api#30]
Guten Tag

Vielen Dank für den tollen Adapter. Hat bis jetzt immer TipTop funktioniert.

Seit ein paar Tagen werden die Daten im ioBroker leider nicht mehr aktualisiert. Im Log gibt's folgende Einträge:

swiss-weather-api.0 | 2021-03-17 08:17:37.429 | error | (119510) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
-- | -- | -- | --
swiss-weather-api.0 | 2021-03-17 08:17:37.428 | error | (119510) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 08:17:37.420 | error | (119510) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 | 2021-03-17 08:17:37.419 | error | (119510) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 08:17:37.414 | error | (119510) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 | 2021-03-17 08:17:37.412 | error | (119510) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 08:17:37.399 | error | (119510) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 | 2021-03-17 08:17:37.398 | error | (119510) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 08:17:36.900 | info | (119510) Swiss-Weather-API: Get Weather Infos...

In MyApps scheint alles in Ordnung zu sein.

Kann mir jemand helfen.

Vielen Dank für die Unterstützung

LG jean

**Comment by baerengraben** [comment]
Hallo Jean

Ja, die letzten Tage war SRG etwas nachlässig. Rund eine Woche lang hat ihr API den Dienst verweigert. Es gab im letzten Jahr hin und wieder mal einen Unterbruch. Die waren aber selten länger als ein Tag. Diese Mal wars fast eine Woche. :(

Ich habe das Thema hier auch Dokumentiert: https://github.com/baerengraben/iobroker.swiss-weather-api/issues/24

Seit heute ca. 10:00 werden die Daten aber wieder geliefert. Kannst du das auch bestätigen?

LG Ralph

**Comment by Luedem25** [comment]
Sali Ralf

Vielen Dank für die Rückmeldung.

Ich habe den Adapter deinstalliert und wieder installiert. Im log kommen folgende Meldungen:

swiss-weather-api.0 	2021-03-17 14:10:35.649 	error 	(134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 	2021-03-17 14:10:35.647 	error 	(134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 	2021-03-17 14:10:35.638 	error 	(134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 	2021-03-17 14:10:35.638 	error 	(134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 	2021-03-17 14:10:35.632 	error 	(134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 	2021-03-17 14:10:35.631 	error 	(134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 	2021-03-17 14:10:35.624 	error 	(134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mom
swiss-weather-api.0 	2021-03-17 14:10:35.623 	error 	(134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 	2021-03-17 14:10:35.340 	info 	(134144) Swiss-Weather-API: Get Weather Infos...
swiss-weather-api.0 	2021-03-17 14:10:25.337 	info 	(134144) longitude/longitude will be set by self-Config - longitude: 8.89854 latitude: 47.55816
swiss-weather-api.0 	2021-03-17 14:10:25.293 	info 	(134144) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.21.0, js-controller: 3.2.16
host.iobrokervm 	2021-03-17 14:10:23.313 	info 	instance system.adapter.swiss-weather-api.0 started with pid 134144
host.iobrokervm 	2021-03-17 14:10:05.766 	info 	Restart adapter system.adapter.swiss-weather-api.0 because enabled
host.iobrokervm 	2021-03-17 14:10:05.765 	error 	instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
swiss-weather-api.0 	2021-03-17 14:10:05.062 	warn 	(134115) Terminated (UNCAUGHT_EXCEPTION): Without reason
swiss-weather-api.0 	2021-03-17 14:10:05.060 	info 	(134115) terminating
swiss-weather-api.0 	2021-03-17 14:10:05.028 	error 	(134115) Unexpected token , in JSON at position 34
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	at processTicksAndRejections (internal/process/task_queues.js:84:21)
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	at endReadableNT (_stream_readable.js:1241:12)
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	at IncomingMessage.emit (events.js:326:22)
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:157:20)
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	at JSON.parse (<anonymous>)
swiss-weather-api.0 	2021-03-17 14:10:05.027 	error 	(134115) SyntaxError: Unexpected token , in JSON at position 34
swiss-weather-api.0 	2021-03-17 14:10:05.024 	error 	(134115) uncaught exception: Unexpected token , in JSON at position 34
swiss-weather-api.0 	2021-03-17 14:10:04.738 	info 	(134115) Swiss-Weather-API: Get Weather Infos...
swiss-weather-api.0 	2021-03-17 14:09:54.806 	info 	(134115) system longitude: latitude:
swiss-weather-api.0 	2021-03-17 14:09:54.734 	info 	(134115) longitude/longitude not set, get data from system
swiss-weather-api.0 	2021-03-17 14:09:54.683 	info 	(134115) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.21.0, js-controller: 3.2.16


LG jean

Mit freundlichen Grüssen
Jean Steinemann

GWV2+2R Frauenfeld

**Comment by Luedem25** [comment]
Sali Ralf

Danke für die Rückmeldung. Ich habe den Adapter deinstalliert und wieder installiert und die Instanz konfiguriert. Folgende Log-Einträge habe ich:


swiss-weather-api.0 | 2021-03-17 14:10:35.649 | error | (134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mo
-- | -- | -- | --
swiss-weather-api.0 | 2021-03-17 14:10:35.647 | error | (134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 14:10:35.638 | error | (134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mo
swiss-weather-api.0 | 2021-03-17 14:10:35.638 | error | (134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 14:10:35.632 | error | (134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mo
swiss-weather-api.0 | 2021-03-17 14:10:35.631 | error | (134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 14:10:35.624 | error | (134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mo
swiss-weather-api.0 | 2021-03-17 14:10:35.623 | error | (134144) Response has announced an error: Invalid API call as no apiproduct match found
swiss-weather-api.0 | 2021-03-17 14:10:35.340 | info | (134144) Swiss-Weather-API: Get Weather Infos...
swiss-weather-api.0 | 2021-03-17 14:10:25.337 | info | (134144) longitude/longitude will be set by self-Config - longitude: 8.89854 latitude: 47.55816
swiss-weather-api.0 | 2021-03-17 14:10:25.293 | info | (134144) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.21.0, js-controller: 3.2.16
host.iobrokervm | 2021-03-17 14:10:23.313 | info | instance system.adapter.swiss-weather-api.0 started with pid 134144
host.iobrokervm | 2021-03-17 14:10:05.766 | info | Restart adapter system.adapter.swiss-weather-api.0 because enabled
host.iobrokervm | 2021-03-17 14:10:05.765 | error | instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
swiss-weather-api.0 | 2021-03-17 14:10:05.062 | warn | (134115) Terminated (UNCAUGHT_EXCEPTION): Without reason
swiss-weather-api.0 | 2021-03-17 14:10:05.060 | info | (134115) terminating
swiss-weather-api.0 | 2021-03-17 14:10:05.028 | error | (134115) Unexpected token , in JSON at position 34
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | at endReadableNT (_stream_readable.js:1241:12)
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | at IncomingMessage.emit (events.js:326:22)
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:157:20)
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | at JSON.parse (<anonymous>)
swiss-weather-api.0 | 2021-03-17 14:10:05.027 | error | (134115) SyntaxError: Unexpected token , in JSON at position 34
swiss-weather-api.0 | 2021-03-17 14:10:05.024 | error | (134115) uncaught exception: Unexpected token , in JSON at position 34
swiss-weather-api.0 | 2021-03-17 14:10:04.738 | info | (134115) Swiss-Weather-API: Get Weather Infos...
swiss-weather-api.0 | 2021-03-17 14:09:54.806 | info | (134115) system longitude: latitude:
swiss-weather-api.0 | 2021-03-17 14:09:54.734 | info | (134115) longitude/longitude not set, get data from system
swiss-weather-api.0 | 2021-03-17 14:09:54.683 | info | (134115) starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.21.0, js-controller: 3.2.16

Vielen Dank.

LG jean

**Comment by Luedem25** [comment]
In den Objekten wurden keine Einträge erstellt, jedoch bei den SystemAdapter.

system.adapter.swiss-weather-api.0

**Comment by baerengraben** [comment]
Ok. Diese Fehlermeldung erstaunt mich:

`(134144) InvalidAPICallAsNoApiProductMatchFound: Wrong SRF-Product is linked to your SRF-App. Please choose the free SRF Product 'SRG-SSR-PUBLIC-API-V2'. Other SRF Prducts are not supported at the mo...`

Insbesondere, weil der Adapter ja schon funktioniert hat.

Die Fehlermeldung besagt, dass du bei der Erstellung der SRG-App nicht das Produkt SRG-SSR-PUBLIC-API-V2 ausgewählt hast.
Kannst du mal auf deinem SRG-Profil unter "MyApps" überprüfen ob die App, welche du im swiss-weather-api Adapter verwendest, auch das Produkt 'SRG-SSR-PUBLIC-API-V2' zugewiesen wird?

**Comment by Luedem25** [comment]
Das war's, Ralph. Vielen Dank für deine Unterstützung. Jetzt funktioniert alles wieder.

Ich wünsche dir einen schönen Abend.

LG jean

**Comment by baerengraben** [comment]
Freut mich :)
Auch einen schönen Abend!
LG
Ralph
