### ISSUE TITLE
Installation nicht erfolgreich

### ISSUE THREAD

**Issue by chrisret0** [baerengraben/ioBroker.swiss-weather-api#33]
Nach erfolgter Installation startet der Weather Adapter nicht. Ich erhalte bei folgendem Commando 

cd /opt/iobroker/
iobroker stop
cd cd /opt/iobroker/node_modules/iobroker.swiss-weather-api/
sudo npm rebuild --unsafe-perm
iobroker start

**diese Warnmeldungen**
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

Log sieht wie folgt aus:

host.rchriobroker | 2021-03-31 20:18:06.501 | error | instance system.adapter.swiss-weather-api.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.rchriobroker | 2021-03-31 20:18:06.501 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/libxmljs2/index.js:4:18)
host.rchriobroker | 2021-03-31 20:18:06.500 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.rchriobroker | 2021-03-31 20:18:06.500 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.rchriobroker | 2021-03-31 20:18:06.500 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.rchriobroker | 2021-03-31 20:18:06.500 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.rchriobroker | 2021-03-31 20:18:06.500 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/libxmljs2/lib/bindings.js:1:37)
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/bindings/bindings.js:126:9)
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/lib/binding/node-v64-linux-arm/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.499 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/addon-build/default/install-root/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.498 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/addon-build/debug/install-root/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.498 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/addon-build/release/install-root/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.498 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/compiled/10.24.0/linux/arm/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.498 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/build/default/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.498 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/Release/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.497 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/out/Release/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.497 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/Debug/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.497 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/out/Debug/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.497 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/build/Release/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.497 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/build/Debug/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.496 | error | Caught by controller[0]: → /opt/iobroker/node_modules/libxmljs2/build/xmljs.node
host.rchriobroker | 2021-03-31 20:18:06.496 | error | Caught by controller[0]: Error: Could not locate the bindings file. Tried:
host.rchriobroker | 2021-03-31 20:18:06.496 | error | Caught by controller[0]: ^
host.rchriobroker | 2021-03-31 20:18:06.496 | error | Caught by controller[0]: throw err;
host.rchriobroker | 2021-03-31 20:18:06.495 | error | Caught by controller[0]: /opt/iobroker/node_modules/bindings/bindings.js:135
host.rchriobroker | 2021-03-31 20:17:41.092 | info | "system.adapter.swiss-weather-api.0" disabled

**Comment by baerengraben** [comment]
Hallo @chrisret0 

Leider kann ich dir nicht wirklich helfen. Irgendwie scheint es ein Problem mit der Library libxmljs2 zu geben. Aber was mich sehr stutzig mach ist, dass dein npm die Node.js Version nicht unterstützen soll:
  
`npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/`

Wie sieht denn deine ioBroker installation aus (Hardware, Software)? Insbesondere: Welche npm version läuft bei dir? ( 'npm -v')

**Comment by baerengraben** [comment]
Bitte mit Version 0.9.0 nochmals versuchen.
