### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [baerengraben/ioBroker.swiss-weather-api#34]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/baerengraben/iobroker.swiss-weather-api

- [x] [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [x] [E004] No adapter name found in URL: https://raw.githubusercontent.com/baerengraben/iobroker.swiss-weather-api/master
- [x] [E020] Name of adapter in package.json must be lowercase and be equal to "iobroker.". Now is "undefined"
- [x] [E019] Invalid repository URL: https://github.com/baerengraben/ioBroker.swiss-weather-api. Expected: git+https://github.com/baerengraben/iobroker.swiss-weather-api.git
- [x] [E103] common.name in io-package.json must be equal to "". Now is swiss-weather-api
- [x] [E150] No common.connectionType found in io-package.json
- [x] [E152] No common.dataSource found in io-package.json
- [x] [E200] Not found on npm. Please publish
- [x] [E301] Tests on Travis-ci.org are broken. Please fix.

I have also found warnings that may be fixed if possible.

- [x] [W400] Cannot find "" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by baerengraben** [comment]
https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/baerengraben/ioBroker.swiss-weather-api
gives no erros => Check!

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
