### ISSUE TITLE
SRG-SSR-PUBLIC-API-V2 is not working anymore

### ISSUE THREAD

**Issue by turtok187** [baerengraben/iobroker.swiss-weather-api#36]
SRG-SSR-PUBLIC-API-V2 is not working anymore, and API requests from 0.3.2 doesn't work on the new Freemium API.

**Comment by baerengraben** [comment]
Yes, I was informed yesterday, that there is now a new API. The old API will be supported for the next 3 months. So I have 3 months to update the adapter...
See also: https://github.com/baerengraben/iobroker.swiss-weather-api/issues/35

**Comment by turtok187** [comment]
I'was not able to connect anymore with my own SRG App Credentials. The Log says that I have to use the Freemium Access.
So I have to find another weather source.
thanks, for me, you can close this issue
