### ISSUE TITLE
Deutsch | ioBroker-Instanz stoppt immer wieder

### ISSUE THREAD

**Issue by Luedem25** [baerengraben/ioBroker.swiss-weather-api#43]
Guten Abend

Erstmals wieder, vielen Dank für die Arbeit. Der Adapter hat immer bestens funktioniert.

Mit der neusten Version 0.9.1  stoppt die Instanz immer wieder, mit folgendem Eintrag im Log:

host.iobrokervm | &nbsp; | 2021-05-25 22:04:24.225 | error | instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | -- | --
swiss-weather-api.0 | 390451 | 2021-05-25 22:04:23.578 | error | Cannot read property 'id' of undefined
swiss-weather-api.0 | 390451 | 2021-05-25 22:04:23.577 | error | TypeError: Cannot read property 'id' of undefined at IncomingMessage.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1714:28) at IncomingMessage.emit (node:events:377:35) at endReadableNT (node:internal/streams/readable:1312:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
swiss-weather-api.0 | 390451 | 2021-05-25 22:04:23.574 | error | uncaught exception: Cannot read property 'id' of undefined

Was mache ich falsch?

Im Voraus vielen Dank für die Unterstützung.

LG jean

**Comment by baerengraben** [comment]
Hallo Jean

Aktuell tippe ich darauf, dass die Adapter-Konfiguration noch nicht stimmt. Hast du eine neue Freemium-App beim SRF Develiper-Portal erstellt und die Credentials (consumerkey und consumersecret)  konfiguriert?

Wenn das nicht hilft:
Um besser helfen zu können, bräuchte ich die debug-logs. Kannst du den Adapter im debug-modus laufen lassen (über den Expertenmodus) und mir die logs hier posten?

LG
Ralph

**Comment by Luedem25** [comment]
Sali Ralph

Vielen Dank für die Rückmeldung. Genau so war's. Neue App lösen und jetzt 
funktioniert es.

Ich wünsche dir einen schönen Abend.

LG Jean



Am 26. Mai 2021 10:44:27 schrieb baerengraben ***@***.***>:

**Comment by baerengraben** [comment]
Super, freut mich dass es geht :)

Ich werde deinen Fehler aber trotzdem noch in der nächsten Version korrigieren. Es sollte in diesem Falle eine informative Fehlermeldung ausgegeben werden ("neue Freemium App installiert?").
