### ISSUE TITLE
Adapter wechselt immer wieder auf gelb

### ISSUE THREAD

**Issue by ralpha1983** [baerengraben/ioBroker.swiss-weather-api#47]
Hallo 
Ich finde Ihren Adapter super. Ich habe nun 0.9.2 installiert und ein Freemium-App bei SRG neu installiert sowie die entsprechenden Keys im Adapter angepasst. Beim Speichern startet der Adapter sofort mit grün, wird aber nach ca. 30 Sekunden gelb. Im Log des ioBroker habe ich rote Log-Einträge: 

invalid date found. Could not assign date. The date received is not one of the coming week. 2021-06-05T00:00:00+02:00

Ist das ein Problem meinerseits oder kommt da was von SRF nicht richtig an?

**Comment by baerengraben** [comment]
Hi @ralpha1983
Dieser Fehler wird geworfen, wenn das Datum des vom SRF gelieferten Datensatz nicht aktuell ist. Um dies zu überprüfen, wird dein Systemdatum gelesen und mit dem Datensatz von SRF verglichen. Wie ich der Fehlermeldung entnehmen kann, ist der Datensatz von SRF korrekt (2021-06-05T00:00:00+02:00). 
Das lässt mich vermuten, dass deine Systemzeit nicht korrekt eingestellt ist. Kannst du das mal überprüfen?

**Comment by ralpha1983** [comment]
Hallo baerengraben

 

Ich habe das soeben überprüft, jedoch kein falsches Datum entdecken können. Weder im ioBroker noch auf dem Server, auf welchem ioBroker ausgeführt wird:

 



 

Zeitanzeige Server:

 



 

 

 



 

 

 

 

 

Freundliche Grüsse

Ralph Ammann

 

Ralph Ammann

Kanzleistrasse 12

CH-4923 Wynau

 

 ***@***.***> ***@***.***

+41 (0)79 883 58 68

 

Von: baerengraben ***@***.***> 
Gesendet: Montag, 7. Juni 2021 10:04
An: baerengraben/ioBroker.swiss-weather-api ***@***.***>
Cc: ralpha1983 ***@***.***>; Mention ***@***.***>
Betreff: Re: [baerengraben/ioBroker.swiss-weather-api] Adapter wechselt immer wieder auf gelb (#47)

 

Hi @ralpha1983 <https://github.com/ralpha1983> 
Dieser Fehler wird geworfen, wenn das Datum des vom SRF gelieferten Datensatz nicht aktuell ist. Um dies zu überprüfen, wird dein Systemdatum gelesen und mit dem Datensatz von SRF verglichen. Wie ich der Fehlermeldung entnehmen kann, ist der Datensatz von SRF korrekt (2021-06-05T00:00:00+02:00).
Das lässt mich vermuten, dass deine Systemzeit nicht korrekt eingestellt ist. Kannst du das mal überprüfen?

**Comment by baerengraben** [comment]
Hi Ralph :)
Merci fürs Feedback. Ok. Ich werde die Logik umschreiben. Mittlerweile gefällt es mir sowieso nicht mehr, dass ich da eine Abhängigkeit zum Datum eingebaut habe. Muss eigentlich gar nicht sein. Ich ändere das (wohl noch heute Abend) und mache dann eine Version 0.9.4 daraus. Danach wäre ich froh, wenn du wieder testen könntest.
LG
Ralph

**Comment by baerengraben** [comment]
Neue Version ist da: 0.9.4 bzw. wird morgen im latest repo erscheinen. Bitte um einen Retest.

**Comment by ralpha1983** [comment]
Hallo

 

Vielen Dank für die Version 0.9.4. Ich habe die Version installiert. Alles ist jetzt richtig:

 

*	Instanz bleibt nun grün, wechselt nicht mehr ständig auf gelb
*	Im Log keine Fehlermeldungen
*	Korrektes Datum in Datenpunkten

 

Ich freue mich 😊

 

Vielen Dank nochmals für den raschen Support!

 

Lg, Ralph

 

Von: baerengraben ***@***.***> 
Gesendet: Dienstag, 8. Juni 2021 11:59
An: baerengraben/ioBroker.swiss-weather-api ***@***.***>
Cc: ralpha1983 ***@***.***>; Mention ***@***.***>
Betreff: Re: [baerengraben/ioBroker.swiss-weather-api] Adapter wechselt immer wieder auf gelb (#47)

 

Neue Version ist da: 0.9.4 bzw. wird morgen im latest repo erscheinen. Bitte um einen Retest.
