### ISSUE TITLE
Implement current_hour

### ISSUE THREAD

**Issue by zImage-de** [baerengraben/ioBroker.swiss-weather-api#49]
Danke für den tollen Adapter.
Kann man nicht die Vorhersage der aktuellen Stunde in einem separatem Datenpunkt sammeln? Das wäre praktisch um immer die Vorhersage der aktuellen Stunde zu visualisieren. In der altern SRG API gab es diesen Datenpunkt .... 
Danke Jochen Christmann

**Comment by baerengraben** [comment]
Hallo Jochen

Diese Anforderung ist bereits umgesetzt. Die "Current_Hour" findest du hier: swiss-weather-api.0.forecast.current_hour
current_hour wird ca. 40s nach dem ersten Start des Adapters erstellt und dann jede Stunde aktualisiert.

**Comment by zImage-de** [comment]
Ich bin gar nicht dazugekommen mich zu bedanken .... Den Datenpunkt Current_Hour gab es bei mir nicht ... hab wohl beim update von 3.x auf aktuelle Version vergessen die Datenstruktur zuvor zu löschen ... hab das jetzt nachgeholt und siehe da mein Wunsch ging in Erfüllung ...
Danke baerengraben
