### ISSUE TITLE
Update Problems

### ISSUE THREAD

**Issue by 6RomN6** [baerengraben/ioBroker.swiss-weather-api#5]
Hi 

I get following Erros if i try to update or install a second Instance

Great Adapter!!! :-D

$ ./iobroker add swiss-weather-api  --host ioBroker-RasPi4
NPM version: 6.13.4npm install iobroker.swiss-weather-api@0.2.0 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code EACCESnpm ERR! syscall unlinknpm ERR! path /opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefilenpm ERR! errno -13
npm ERR! Error: EACCES: permission denied, unlink '/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile'npm ERR!  { [Error: EACCES: permission denied, unlink '/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile']npm ERR!   cause:npm ERR!    { Error: EACCES: permission denied, unlink '/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile'npm ERR!      errno: -13,npm ERR!      code: 'EACCES',npm ERR!      syscall: 'unlink',npm ERR!      path:npm ERR!       '/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile' },npm ERR!   stack:npm ERR!
    'Error: EACCES: permission denied, unlink \'/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile\'',npm ERR!   errno: -13,npm ERR!   code: 'EACCES',npm ERR!   syscall: 'unlink',npm ERR!   path:npm ERR!    '/opt/iobroker/node_modules/.libxmljs2.DELETE/build/Makefile',npm ERR!   parent: 'iobroker' }
npm ERR! npm ERR! The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-03-27T20_54_21_983Z-debug.log
ERROR: host.ioBroker-RasPi4 Cannot install iobroker.swiss-weather-api@0.2.0: 243
ERROR: process exited with code 25

**Comment by baerengraben** [comment]
Hi
That's strange. On my test system as well as on my productive system I can easily install multiple instances. Your error message shows that he has a problem with permissions.
You were able to install a first instance without problems? Only with the second installation you get this error?

**Comment by 6RomN6** [comment]
Ich bin nicht so stark auf englisch, deshalb zuerst in Deutsch... 
Zuerst hatte ich nur eine Instanz welche ich versuchte zu Updaten, wobei ich scheiterte mit der selben Meldung (meine ich zumindest) danach habe ich versucht eine zweite Instanz zu installieren. was mit dieser Fehlermeldung geendet hat.

Das einzige was ich an den Permissions rumgebastelt habe war der root-zugriff per ssh meine ich, wobei ich das Rootpasswort noch setzten konnte und dann aber die Config-Datei nicht so abändern konnte wie es in dem verwendeten Tutorial angegeben war. Dies endete wegen mangelnder Kenntnisse dann damit.

First i tried to update my first instance but i failed, i think with same error-message. After that i tried to install a second instance with the error-message i posted before...

The only thing i changed at the Permissions was something at the root permissions via ssh i think i used a tutorial but i failed... but i have set a root password.

**Comment by baerengraben** [comment]
Sorry für die späte Antwort. Irgendwie hat mich Github nicht über deinen Eintrag informiert...

Offensichtlich hat die erste Installation noch funktioniert. Hast du anschliessen das Tutorial mit dem Root-Passwort durchgeführt? Hast du mir den Link zum Tutorial, welches du verwendet hast?

**Comment by baerengraben** [comment]
@6RomN6 : Ich hatte heute das selbe Problem auf einer meiner Dev-Umgebungen. Es handelte sich bei mir tatsächlich um ein Berechtigungsproblem. Bitte Checke User/Gruppe und Permissions in /opt/iobroker/node_modules/.libxmljs2.DELETE

**Comment by 6RomN6** [comment]
Sorry für mein delay, ich musste mich die letzte Zeit Corona-bedingt mit anderen Themen auseinandersetzen :-D, mit dem Fix waren die Permissionprobleme behoben würde ich sagen, muss aber gestehen dass ich diesen im Zuge des Node Updates durchgeführt habe, und dann den Adapter nochmals installiert habe... sprich ich habe diverse Dinge getan und nicht nur im Bezug auf deinen Adapter getestet.
