### ISSUE TITLE
JsonChart is missing 15h and 16h as x-labels

### ISSUE THREAD

**Issue by jobe451** [baerengraben/ioBroker.swiss-weather-api#54]
betrifft: swiss-weather-api.0.forecast.60minutes.day0.JsonChart (wahrscheinlich auch die anderen Tage)

Die axisLabels umfassen nur 22 Elemente statt 24. 15h und 16h fehlen. Die übrigen Daten umfassen jeweils 24 Felder.

Beispiel:
`{
    "axisLabels": [
        "1h",
        "2h",
        "3h",
        "4h",
        "5h",
        "6h",
        "7h",
        "8h",
        "9h",
        "10h",
        "11h",
        "12h",
        "13h",
        "14h",
        "17h",
        "18h",
        "19h",
        "20h",
        "21h",
        "22h",
        "23h",
        "24h"
    ],
    "graphs": [
        {
            "data": [
                19,
                18,
`

**Comment by baerengraben** [comment]
Vielen Dank fürs korrigieren mittels Pull-Reqeust!
