### ISSUE TITLE
Latitude / Longitude von ioBroker verwenden

### ISSUE THREAD

**Issue by UncleSamSwiss** [baerengraben/iobroker.swiss-weather-api#6]
Hallo Bärengraben,

Genialer Adapter! ioBroker hat in der Config eigentlich schon die Koordinaten drin, könntest du nicht einfach diese verwenden für die Lokalisierung? Sollte irgendwo in der Global Config liegen (ich weiss gerade nicht auswändig, wo).

/UncleSam

**Comment by baerengraben** [comment]
Hi UncleSam
Gute Idee. :+1:  Dem gehe ich mal nach.

**Comment by baerengraben** [comment]
Mit der Version 0.3.1 sind longitude und latitude in der Adapter-Konfig optional. Wenn nicht gesetzt, wird die system longitude/latitude geladen.
