### ISSUE TITLE
Tornado

### ISSUE THREAD

**Issue by trevon88** [baerengraben/ioBroker.swiss-weather-api#60]
Hallo,

Ich habe ein Problem.

Das Wetter wird bei mir nur noch als "Tornado" angezeigt. Es lief aber eigentlich immer.

Auch sehe ich auf der SRG Seite das die Daten abgerufen werden.
In denn Objekten bekomme ich aber nur "Invalid Date" + "Null".

Haben die was geändert bei der API?

**Comment by trevon88** [comment]
Ah, anscheinend kommt der "Aktuelle" Stunden / Minuten - WErt nicht mehr. Alle anderen Daten sind vorhanden..

**Comment by baerengraben** [comment]
Hi @trevon88 

Nein, geändert hat bisher nichts. Kannst du mir genauer sagen, welcher Wert bei dir nicht mehr ankommt? (z.B. swiss-weather-api.0.forecast.current_hour) 

Welche Version des Adapters verwendest du?

**Comment by baerengraben** [comment]
timeout => probably duplicate to https://github.com/baerengraben/ioBroker.swiss-weather-api/issues/51
