### ISSUE TITLE
Not set default language in iobroker => crash

### ISSUE THREAD

**Issue by florian1984** [baerengraben/ioBroker.swiss-weather-api#62]
If you not set a default language in Iobroker, the adapter crash:

RangeError: Incorrect locale information provided at Date.toLocaleString (<anonymous>) at getDayName (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:94:18) at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2039:18 at Array.forEach (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2030:26) at IncomingMessage.emit (node:events:406:35) at endReadableNT (node:internal/streams/readable:1343:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)

After settings default language in iobroker everything works fine again.

**Comment by baerengraben** [comment]
Actually, the adapter should use "en-GB" as default language in this case. But this seems not to have worked. Made a correction. Now "de" is the used language if no default language is set in ioBroker. I wanted to test this now. But now I wonder how you could not set a default language in ioBroker. The admin panel require a default language. How did you remove the language there?
