### ISSUE TITLE
date value of object "info/lastrun" not correct

### ISSUE THREAD

**Issue by guggu1** [baerengraben/ioBroker.swiss-weather-api#67]
Thanks for the really useful adapter.

I have discovered that the month of the date value in object "info/lastrun" is not correct. It reads "10", for example, in the month of November. I.e. it should read "11". The time in minutes and seconds is correct.

The error is very likely due to the fact that in JS months are numbered from 0, whereas in real life numbering is from 1.

Thanks for correcting this. I use the lastrun value to show how recent my weather data are.

Christoph S

**Comment by baerengraben** [comment]
Hi @guggu1 
Wow...Indeed. Thanks for reporting this. I will correct this as soon as possible.

**Comment by guggu1** [comment]
the job of the tester is to prove that it does NOT work!  ;-))

Christoph

**Comment by baerengraben** [comment]
Resolved with next release

**Comment by baerengraben** [comment]
Fixed in https://github.com/baerengraben/ioBroker.swiss-weather-api/releases/tag/1.0.3
