### ISSUE TITLE
Sommer/Winterzeit - Umstellung wirkt sich auf Objekteerstellung aus

### ISSUE THREAD

**Issue by ralpha1983** [baerengraben/ioBroker.swiss-weather-api#78]
Hallo, seit Sonntag, 27.03.2022 werden die Objekte nicht mehr aktualisiert. Alle Forcast unter "day" haben das selbe Datum. 
Ist etwas dahingehend bekannt? Vielen Dank

**Comment by baerengraben** [comment]
Hi @ralpha1983 

Aufgefallen ist mir bis jetzt nichts. Habe es aber jetzt noch genau geprüft. Die Forecasts

- forecast/60minutes
- forecast/current_hour
- forecast/day

sind bei mir korrekt.

Aber nach forecast/hour/dayx/xxxx/local_date_time werden tatsächlich sonderbare Daten abgefüllt:

0100/local_date_time = 2022-03-27T01:00:00+01:00
0200/local_date_time = 2022-04-05T02:00:00+02:00
0400/local_date_time = 2022-03-26T04:00:00+01:00
0500/local_date_time = 2022-04-05T05:00:00+02:00
0700/local_date_time = 2022-03-26T07:00:00+01:00
0800/local_date_time = 2022-04-05T08:00:00+02:00
1000/local_date_time = 2022-03-26T10:00:00+01:00
1100/local_date_time = 2022-04-05T11:00:00+02:00
1300/local_date_time = 2022-03-26T13:00:00+01:00
1400/local_date_time = 2022-04-05T14:00:00+02:00
1600/local_date_time = 2022-03-26T16:00:00+01:00
1700/local_date_time = 2022-04-05T17:00:00+02:00
1900/local_date_time = 2022-03-26T19:00:00+01:00
2000/local_date_time = 2022-04-05T20:00:00+02:00
2200/local_date_time = 2022-03-26T22:00:00+01:00
2300/local_date_time = 2022-04-05T23:00:00+02:00

Kann es sein, dass du am Sonntag den Adapter auf eine neue Version aktualisiert hast?

**Comment by ralpha1983** [comment]
Hallo 

 

Ich habe am Adapter selber nichts geupdatet. Bin auf der Version 1.0.3.

 

Ich denke, dass dies seit der Sommerzeit-Umstellung auftritt. Was mir auffällt, das z.B. bei forecast/day/day0 ein Ordner 2200 und 2300 existiert.

Bei 2200 ist das Datum korrekt, bei 2300 blieb es auf 27.03.2022 stehen. Somit denke ich, dass im Sommerhalbjahr die Daten in 2200 abgefüllt und im Winterhalbjahr die Daten in 2300 abgefüllt werden.

 

 

Freundliche Grüsse

Ralph Ammann

 

 

Von: baerengraben ***@***.***> 
Gesendet: Dienstag, 5. April 2022 21:10
An: baerengraben/ioBroker.swiss-weather-api ***@***.***>
Cc: ralpha1983 ***@***.***>; Mention ***@***.***>
Betreff: Re: [baerengraben/ioBroker.swiss-weather-api] Seit 27.03.2022 werden die Objekte nicht mehr aktualisiert (Issue #78)

 

Hi @ralpha1983 <https://github.com/ralpha1983> 

Aufgefallen ist mir bis jetzt nichts. Habe es aber jetzt noch genau geprüft. Die Forecasts

*	forecast/60minutes
*	forecast/current_hour
*	forecast/day

sind bei mir korrekt.

Aber nach forecast/hour/dayx/xxxx/local_date_time werden tatsächlich sonderbare Daten abgefüllt:

0100/local_date_time = 2022-03-27T01:00:00+01:00
0200/local_date_time = 2022-04-05T02:00:00+02:00
0400/local_date_time = 2022-03-26T04:00:00+01:00
0500/local_date_time = 2022-04-05T05:00:00+02:00
0700/local_date_time = 2022-03-26T07:00:00+01:00
0800/local_date_time = 2022-04-05T08:00:00+02:00
1000/local_date_time = 2022-03-26T10:00:00+01:00
1100/local_date_time = 2022-04-05T11:00:00+02:00
1300/local_date_time = 2022-03-26T13:00:00+01:00
1400/local_date_time = 2022-04-05T14:00:00+02:00
1600/local_date_time = 2022-03-26T16:00:00+01:00
1700/local_date_time = 2022-04-05T17:00:00+02:00
1900/local_date_time = 2022-03-26T19:00:00+01:00
2000/local_date_time = 2022-04-05T20:00:00+02:00
2200/local_date_time = 2022-03-26T22:00:00+01:00
2300/local_date_time = 2022-04-05T23:00:00+02:00

Kann es sein, dass du am Sonntag den Adapter auf eine neue Version aktualisiert hast?

**Comment by baerengraben** [comment]
Das kann tatsächlich sein. In diesem Falle wäre das naütrlich ein Bug. Ich werde dem noch weiter nachgehen.

Fix für die Zwischenzeit:

-     Stoppe Adapter
-     Lösche alle Objekte unter swiss-weather-api/0
-     Starte Adapter neu

**Comment by baerengraben** [comment]
Neu kann die Zeitzone im SRF-Developer Portal gesetzt werden (unter Profile):

![Bildschirmfoto vom 2023-02-27 08-34-19](https://user-images.githubusercontent.com/9572444/221502166-4b70902c-354a-46f1-9b02-2ff9388b2fc4.png)

Mal schauen ob damit das Problem bei der nächsten Zeitumstellung gelöst ist.

**Comment by baerengraben** [comment]
Die Sommerzeit hat Einzug gehalten. Leider besteht das Problem weiterhin:

Die Vorhersagen unter `forecast/hour` halten nach der Zeitumstellung einerseits noch alte Objekte aus der Winterzeit und andererseits neue Objekte aus der Sommerzeit.

Alle anderen Forcasts (60minutes, current_hour, day) sind nicht betroffen. Diese sind auch nach der Zeitumstellung korrekt.

Workaround:

- Löschen der Objekte `forecast/hour` (ganzer Objektbaum). Der Adapter wird die Einträge beim nächsten Update korrekt erstellen.

**Comment by baerengraben** [comment]
Es besteht eine kleine Wahrscheinlichkeit, dass SRF diese Problem mit der neuen API Version 2 gelöst hat. Neu sind die betroffenen Objekte in swiss-weather-api.0.forecast.three_hours.* abgelegt.

Die Korrektur, was eher ein unschöner "Hack" ist, soll entfernt werden und dann die nächste Zeitumstellung abgewartet werden.

**Comment by baerengraben** [comment]
Das Problem besteht weiterhin. 

Das Problem kann wohl am besten folgendermassen behoben werden:
- Bei jeder Abfrage swiss-weather-api.0.forecast.three_hours.* löschen
- Bei jeder Iteration von three_hours die konkrete Stunde aus swiss-weather-api.*.forecast.three_hours.*.*.date_time lesen und Objekte entsprechend erstellen.

Damit werden die Stunden dynamsich, analog den konkreten Stunden, erstellt.

**Comment by baerengraben** [comment]
Grundsätzlich schreibt er Adapter einfach 1:1 die Werte, welche SRG sendet in ioBroker Objekte. Damit man die Objekte besser in Visu etc. integrieren kann, strukturiere ich die angelieferten Daten. 

Für three_hours z.b. nach "swiss-weather-api.0.forecast.three_hours.day1.0100".  Wobei 0100 der effektiv von SRF gelieferten Stunde entspricht. Hier wird also z.B. "02.11.2024 **01**:00:00" geliefert.

Aus irgend einem Grunde liefert SRG in der Sommerzeit "02.11.2024 **02**:00:00" und in der Winterzeit "02.11.2024 **01**:00:00".

Daraus resultiert, dass im ioBroker Objekt-Tree dann in der Sommerzeit die 0100 Objekte aktualisiert werden und in der Winterzeit die 0200 Objekte. Damit kann natürlich dann keine anständige Visu erstellt werden.

Ich habe mich nun entschieden für die three_hours Objekte eine Laufnummer zu vergeben:
- Für 0100 oder 0200 wird 1 
- Für 0400 oder 0500 wird 2
- usw.

Falls jemand die three_hours Objekte integriert hat, muss dies nun neu berücksichtigt werden.

**Comment by baerengraben** [comment]
Fixed in https://github.com/baerengraben/ioBroker.swiss-weather-api/releases/tag/v2.2.1
