### ISSUE TITLE
Change max temp to 40

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#81]
https://github.com/baerengraben/ioBroker.swiss-weather-api/blob/af7dc464c03987ef7db60a5e01ffaafb7ac6e40d/main.js#L219

In the graph displayed maximum temperature is 30. Meanwhile, in summer it is sometimes much warmer than 30 degrees. Therefore, this value should be increased to 38 or even 40 degrees.

perhaps the min_temp =0 is also not ideal. Better would be max=38 and min =-15

**Comment by abeggled** [comment]
Please set the lower limit to -20 or -25°C

**Comment by SwissSteini** [comment]
I prefere a dynamic Version. Analyse the Temperature of the Day (24 Values) and define after that the limits. 
like yAxis_max = (Max Value of the Day) +5 and yAxis_min = (Min Value of the Day) -5

Perfect Chart for every Temperature :)

Gruss aus Bern

**Comment by baerengraben** [comment]
@SwissSteini: Your proposal is implemented. Wait for next release und Gruss aus Bern :)

**Comment by baerengraben** [comment]
Fixed with release 1.0.5
