### ISSUE TITLE
Backup iob zeigt Fehlermeldung

### ISSUE THREAD

**Issue by Zerpac54** [baerengraben/ioBroker.swiss-weather-api#84]
Seit kurzem bemerke ich folgende folgende Fehlermeldung:
<html>
<body>

backitup.0 | 2022-09-24 15:31:15.450 | error | [iobroker/iobroker] host.raspberrypi Please ensure that self-created JSON files are valid
-- | -- | -- | --
backitup.0 | 2022-09-24 15:31:15.443 | error | [iobroker/iobroker] host.raspberrypi One or more optional files are corrupted: host.raspberrypi /opt/iobroker/node_modules/iobroker.js-controller/tmp/backup/files/vis.0/Wetter/ioBroker.swiss-weather-api-master/responseSRFWeatherForecast.json is not a valid json file

</body>
</html>

**Comment by baerengraben** [comment]
Hi @Zerpac54 
Ich habe hier seit einigen Monaten nichts mehr an diesen Files geändert. Wenn diese Fehlermeldung erst seit kurzem erscheint, könnte es auch an einem Update von BackItUp liegen. Nichts desto trotz: Diese Files waren lediglich eine Hilfe bei der Entwicklung. Bevor ich da Zeit für eine Analyse investiere, werde ich die in der nächsten Version die beispiel-json Files einfach rauslöschen. => Der Adapter funktioniert auch ohne diese Files.

**Comment by Zerpac54** [comment]
Das sehe ich auch so, danke für die schnelle Beantwortung. Eine Frage hätte ich, kann ich diese Files selber löschen?Freundliche GruesseRobert CaprezAm 26.09.2022 um 09:10 schrieb baerengraben ***@***.***>:﻿
Hi @Zerpac54
Ich habe hier seit einigen Monaten nichts mehr an diesen Files geändert. Wenn diese Fehlermeldung erst seit kurzem erscheint, könnte es auch an einem Update von BackItUp liegen. Nichts desto trotz: Diese Files waren lediglich eine Hilfe bei der Entwicklung. Bevor ich da Zeit für eine Analyse investiere, werde ich die in der nächsten Version die beispiel-json Files einfach rauslöschen. => Der Adapter funktioniert auch ohne diese Files.

**Comment by baerengraben** [comment]
Ja, das weglöschen von 

- responseSRFWeatherForecast.json
- responseSRFWeatherGeolocationByLatitudeLongitude.json
- responseSRFWeatherGeolocationNames.json

ist möglich. Der Adapter wird auch ohne die funktionieren.

**Comment by Zerpac54** [comment]
Danke, aber da muss ich passen😉Freundliche GruesseRobert CaprezAm 26.09.2022 um 09:42 schrieb baerengraben ***@***.***>:﻿
Ja, das weglöschen von

responseSRFWeatherForecast.json
responseSRFWeatherGeolocationByLatitudeLongitude.json
responseSRFWeatherGeolocationNames.json

ist möglich. Der Adapter wird auch ohne die funktionieren.

**Comment by Zerpac54** [comment]
Hallo

Habe gerade bemerkt, dass die Vis nur hellgrau erscheint und ich kann keine andere Views mehr wählen, hast du eine Idee?



Von meinem iPad gesendet
