### ISSUE TITLE
Abfrage funktioniert seit heute Mittag nicht mehr

### ISSUE THREAD

**Issue by EschLuAB** [baerengraben/ioBroker.swiss-weather-api#85]
Seit heute Mittag kommt folgende Meldung vier mal, wenn ich den Adapter starte:

This should never happen. Please rerun adapter with debug-level and report it on https://github.com/baerengraben/ioBroker.swiss-weather-api/issues

Leider habe ich das mit dem dem "adapter with debug-level" nicht geschafft.

**Comment by mi1985** [comment]
Habe das gleiche Problem. Debug angehängt. 
[forecast.log](https://github.com/baerengraben/ioBroker.swiss-weather-api/files/9964473/forecast.log)
`

**Comment by EschLuAB** [comment]
Heute Morgen wieder probiert und es funktioniert wieder.
Das Problem scheint auf der gegenüberliegenden Seite gelegen zu haben und behoben worden zu sein.

**Comment by EschLuAB** [comment]
Seit heute 10 Uhr wieder der gleiche Effekt.

**Comment by spoeh-man** [comment]
Ja bei mir leider auch

**Comment by Matt77CHE** [comment]
ebenso bei mir

**Comment by baerengraben** [comment]
Ich kann es bestätigen - schaue woran es liegt.

**Comment by baerengraben** [comment]
SRF liefert neu irgendwie einen Tag mehr als vorher. Mein Adapter konnte damit umgehen, wenn weniger Daten als versprochen geliefert wurden. Aber nicht, wenn mehr als versprochen geliefert wird. Hm... Das hätte ich jetzt irgendwie wirklich nicht für möglich gehalten ;) An dieser Stelle war mein Code schlussendlich zuwenig robust.

Ich habe einen Fix auf Github eingestellt. Aber leider kann ich nicht testen, weil  meine Anfrage-Limitte für heute schon wieder aufgebraucht ist.

Ich fahre morgen mit meinen Tests fort. Für Ungeduldige:  Einmal den Adapter von Github installieren und hoffen, dass ich bereits beim ersten Commit das Problem erschlagen habe. => Falls dem so wäre, bitte ich um Feedback

**Comment by EschLuAB** [comment]
Übrigens: pro Mailadresse ein Account. Wenn man beim Adapter zwei Accounts eingeben könnte und er alternierend einen wählt, oder zählt und bei aufgebrauchter Limite wechselt, könne ich mehrmals am Tag rebooten ohne immer daran denken zu müssen, dass ich den Adapter immer vorher ausschalten müsste. ;-)

**Comment by EschLuAB** [comment]
Funktioniert leider nicht.

[debug.pdf](https://github.com/baerengraben/ioBroker.swiss-weather-api/files/9983217/debug.pdf)

**Comment by baerengraben** [comment]
Merci für den Test!

Mein moralischer Kompass hat mich bisher davon abgehalten sowas zu implementieren. Leider gibt  es von Seiten SRF auch keine Möglichkeit eine Meldung zu erhalten, wenn sie was am API ändern. Dadurch muss ich oft  kurzfristig reagieren. Und wenn ich dann nach mittlerweile nur noch 25 Requests wieder warten muss... Evtl. implementiere ich das mal im Sinne einer Entwicklungshilfe.

**Comment by baerengraben** [comment]
@EschLuAB 
Bei mir scheint es jetzt wieder zu funktionieren. Wenn du nochmals Zeit hast, bitte ich um ein Retest. Adapter löschen und neu über Github installieren.

**Comment by EschLuAB** [comment]
Habe es installiert. Bin mir nicht sicher ob ich etwas nicht verstanden habe, aber ich musste v1.0.3 normal installieren und dann die github - Version darüber. Wenn ich nach dem löschen nur die github - Version installiert habe, habe ich den Adapter nicht gesehen.
Egal, aber nach dem starten ist keine Fehlermeldung mehr gekommen. Schaue dann morgen Morgen und melde mich, ob alles noch grün ist. Danke.

Und wegen dem anderen Thema: Macht Dich sympatisch und finde es gut, wenn Du meinem Input gegenüber standhaft bleibst :-)
Luxusproblem ;-)

**Comment by EschLuAB** [comment]
Der Adapter funktioniert immer noch (keine Fehlermeldungen) und tut was er tun muss.
Merci @baerengraben

**Comment by pehon** [comment]
github Version darüber installiert - funktioniert wieder, danke!

**Comment by mi1985** [comment]
funktioniert bei mir auch wieder. Schliesse mich dem Luxusproblem an. Evt. kann man dem Adapter auch beibringen die Request in einem bestimmten Zeitfenster zu nutzten. Ich benötige zum Beispiel keine aktuellen Wetterdaten in der Nacht, dafür würde ich gerne die Request intensiver am Tag nutzen.

**Comment by baerengraben** [comment]
Alles klar, Merci für die Tests!

Ich werde dieses Weekend eine neue Version publishen.

**Comment by Aare07** [comment]
Fehler wurde auch bei mir durch die aktuelle Git Version behoben
Merci

**Comment by baerengraben** [comment]
Merci für die Tests. Ich habe eine neue Version 1.0.4 erstellt (npm), welche bald im Beta-Repo erscheinen sollte.

**Comment by baerengraben** [comment]
Fixed mit V 1.0.4
