### ISSUE TITLE
This should never happen. Please rerun adapter with debug-level and report it

### ISSUE THREAD

**Issue by UrsKobler** [baerengraben/ioBroker.swiss-weather-api#87]
Ich erhalte seit einigen Tagen regelmässig die Fehlermeldung "This should never happen. Please rerun adapter with debug-level and report it". Nachdem ich den Debug-Mode eingeschaltet habe, werden folgende Ausgaben in das LOG-Protokoll geschrieben (siehe Datei protocol.log).
[protocol.log.txt](https://github.com/baerengraben/ioBroker.swiss-weather-api/files/9997995/protocol.log.txt)

**Comment by baerengraben** [comment]
Ist ein Duplicate zu https://github.com/baerengraben/ioBroker.swiss-weather-api/issues/85

Bitte aus dem Beta-Repo die neueste Version 1.0.4 installieren. Dann sollte es wieder funktionieren. Die neue Version wird dann per Ende dieser Woche auch auf dem Stable-Repo verfürgbar werden.

**Comment by baerengraben** [comment]
Fixed mit V 1.0.4
