### ISSUE TITLE
60 Minute Forecast for day 4 is incomplete

### ISSUE THREAD

**Issue by knowhowseeker** [baerengraben/ioBroker.swiss-weather-api#91]
![image](https://user-images.githubusercontent.com/41070573/220166770-abc7db06-2a88-4d2b-8e9d-4b946fd4fdf9.png)

**Comment by knowhowseeker** [comment]
I deleted the adpater and reinstalled everthing. The problem is gone.

**Comment by baerengraben** [comment]
The SRF API provides only the first two hours (00:00 and 01:00) for the fourth day. This problem will probably persist even after reinstalling the adapter.
