### ISSUE TITLE
Update auf SRF Meteo V2

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#94]
SRF hat eine neue API-Version veröffentlich: https://developer.srgssr.ch/api-catalog/srf-weather/srf-weather-description

Die bisherige Version V1 wird noch ein Jahr weiterlaufen.

Der Adapter soll auf Version 2 aktualisiert werden.

**Comment by sttetet** [comment]
Hallo @baerengraben 
Wollte den Adapter installieren, aber unter SRF können wenn ich mich nicht täusche nur noch v2 API Keys gelöst werden. Damit startet der Adapter mit einem Fehler. 
Gibt es noch eine Möglichkeit einen V1 Key zu bekommen? Oder sollte es auch so funktionieren?
Danke für die Unterstützung

**Comment by baerengraben** [comment]
@sttetet 
Tatsächlich. Sie haben die Möglichkeit entfernt, Keys für die V1-API zu lösen. Das war mir bislang nicht bewusst. Das bedeutet, dass ich doch nicht soviel Zeit habe die neue Version zu implementieren, wie bisher gedacht :(
Merci für den Hinweis!

**Comment by baerengraben** [comment]
V2-API ist nun integriert. Bitte um Test: https://github.com/baerengraben/ioBroker.swiss-weather-api/releases/tag/v2.0.2

**Comment by sttetet** [comment]
Wow, das ging ja schnell! Vielen Dank!
Ich wollte das gleich testen, kann den Adapter aber nicht via Github installieren. Via normalem Adapter install erscheint immer noch die ältere Version. Wenn ich via Experten Modus von Github oder auch einer URL installiere. Bleibt er mit folgendem Log stehen:
![image](https://github.com/baerengraben/ioBroker.swiss-weather-api/assets/46006363/d04e1049-a0a8-49b1-a0a9-0c82f50e3dfe)

Mache ich etwas falsch, oder müsste das so funktionieren?

**Comment by sttetet** [comment]
@baerengraben 
Fehlalarm, nach einem Neustart hat es nun funktioniert. Aber jetzt erscheint folgender Fehler:

![image](https://github.com/baerengraben/ioBroker.swiss-weather-api/assets/46006363/c9c45e77-0567-40b3-88e6-fe9b67012c17)

**Comment by baerengraben** [comment]
Hi @sttetet 

Tatsächlich wollte ich das noch vor dem 1. August fertig haben ;)

Habe gerade noch eine frische Installation bei mir getestet. Bei mir geht's soweit. 
ioBroker wird die neue Verison wohl erst morgen im "latest" Repo haben. Wenn du heute testen möchtest, installier den Adapter bitte über NPM. Die aktuellste Version ist V2.0.2:

1. Allfällige Instanzen und den Adapter komplett löschen
2. Dann mittels Experten-Modus den Adapter aus NPM installieren. => Hier musst du bis zum swiss-weather-api Adapter etwas runter scrollen.
3. Jetzt installieren => Es wird automatisch Version 2.0.2 installiert
4. Jetzt aus dem installieren Adapter eine neue Instanz erstellen
5. Im Instanzen-Menu den Adapter konfigurieren. => Jetzt brauchst du einen "Freemium V2" Consumer Key & Secret
6. Jetzt noch die Views (Oder "views" aus Github) im Vis-Adapter importieren

Falls es nicht geht, bitte den Debug-Modus aktivieren und mir das hier hinzufügen.

**Comment by Matt77CHE** [comment]
Bei mir das selbe Problem, selbes Log (habe auch 2.0.2 installiert)

**Comment by baerengraben** [comment]
Die Anfrage selber funktioniert schon mal. Aber da ist noch etwas mit der poi-id. Ich schaue es mir an.

**Comment by abeggled** [comment]
> Bei mir das selbe Problem, selbes Log (habe auch 2.0.2 installiert)

bei mir das Selbe, unabhängig ob Update oder wie empfohlen Neuinstallation

**Comment by baerengraben** [comment]
Jetzt habe ich das Problem erkannt. Update folgt!

**Comment by baerengraben** [comment]
Es steht ein neuer Patch-Release v2.0.3 bereit. Hoffe ich konnte das Problem damit beheben und bitte um Test.

**Comment by abeggled** [comment]
Vielen dank, funktioniert wieder!

**Comment by baerengraben** [comment]
Fixed mit v2.0.3
