### ISSUE TITLE
Ortsname und Wochentage werden nicht angezeigt, keine Details Tag 0 - 4

### ISSUE THREAD

**Issue by byteschubser** [baerengraben/ioBroker.swiss-weather-api#95]
In der Übersicht (Wettervorhersagen.json) werden Ortsname und Wochentage nicht angezeigt. Die Lokations-Daten, welche von der API kommen sind aber korrekt. Zur Ermittlung der Wochentage kann ich mangels know how nichts sagen 
![location](https://github.com/baerengraben/ioBroker.swiss-weather-api/assets/3648771/9e240246-c55e-4c00-bb5b-48a913a1bd7f)
![view_wetter](https://github.com/baerengraben/ioBroker.swiss-weather-api/assets/3648771/5a525e27-38cb-43cf-9675-4c502e6ff491)
Wenn ich in der Übersicht auf die Lupe für die Details klicke passiert nichts - es werden keine Details angezeigt

**Comment by baerengraben** [comment]
@byteschubser Das sind gleich mehrere Fragen. ;)

- Übersicht & Lupe: Es gibt im Repo zwei Imports für die Übersicht. Eine mit und eine ohne Overlay. Versuche es mal mit diesem: https://github.com/baerengraben/ioBroker.swiss-weather-api/blob/master/views/Wettervorhersagen_with_Overlay

- Den Ortsnahmen übernehme ich aktuell nicht direkt aus den Objekten. Einfach auf den Text "Ortsname" klicken und unter Eigenschaften=>HTML den Ortsnamen eingeben. / Das wäre aber eigentlich eine gute Idee, diesen direkt aus den Objekten zu lesen. Das nehme ich dann als Erweiterung für die nächsten Version auf.

-  Die Wochentage müssten eigentlich übernommen werden. Funktioniert dies auch mit "Wettervorhersagen_with_Overlay" nicht?
