### ISSUE TITLE
Vis Seite erstellt im iob, sieht i.O aus. In der Vis wird diese aber nur hellgrau dargestellt, was mache ich falsch?

### ISSUE THREAD

**Issue by Zerpac54** [baerengraben/ioBroker.swiss-weather-api#96]

**Comment by baerengraben** [comment]
@Zerpac54 Da bräuchte ich etwas mehr context. Kannst du einen Printscreen beifügen?

**Comment by Zerpac54** [comment]
Danke es hat sich erledigt, es war eine Einstellung in der Vis.Von meinem iPad gesendetAm 05.07.2023 um 21:19 schrieb baerengraben ***@***.***>:﻿
@Zerpac54 Da bräuchte ich etwas mehr context. Kannst du einen Printscreen beifügen?
